site_name: 医学微视
site_url: https://yxws.zhihu.blog/
site_author: shutouyabo
site_description: >-
  wiki bin

repo_name: 医学微视
repo_url: https://github.com/shutouyabo/yixueweishi/

copyright: Copyright &copy; 2021-present <a href="https://github.com/shutouyabo" target="_blank" rel="noopener noreferrer">shutouyabo</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true

  - search:
      lang:
        - zh
  - git-revision-date:
  - minify:
      minify_html: true
  - open-in-new-tab:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shutouyabo/yixueweishi/
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - 前言: "index.md"
  - 1 妇产科疾病 （124）:
      - "1.1 瘢痕妊娠": "1 妇产科疾病 （124）/1.1 瘢痕妊娠.md"
      - "1.2 剖宫产后再生育注意事项": "1 妇产科疾病 （124）/1.2 剖宫产后再生育注意事项.md"
      - "1.3 剖宫产麻醉": "1 妇产科疾病 （124）/1.3 剖宫产麻醉.md"
      - "1.4 保胎": "1 妇产科疾病 （124）/1.4 保胎.md"
      - "1.5 备孕": "1 妇产科疾病 （124）/1.5 备孕.md"
      - "1.6 闭经": "1 妇产科疾病 （124）/1.6 闭经"
      - "1.7 避孕": "1 妇产科疾病 （124）/1.7 避孕"
      - "1.8 剖宫产术后护理": "1 妇产科疾病 （124）/1.8 剖宫产术后护理"
      - "1.9 产后避孕": "1 妇产科疾病 （124）/1.9 产后避孕"
      - "1.10 产后出血": "1 妇产科疾病 （124）/1.10 产后出血"
      - "1.11 产后尿失禁": "1 妇产科疾病 （124）/1.11 产后尿失禁"
      - "1.12 产后排气、通便的治疗": "1 妇产科疾病 （124）/1.12 产后排气、通便的治疗"
      - "1.13 产后盆底功能恢复": "1 妇产科疾病 （124）/1.13 产后盆底功能恢复"
      - "1.14 产后缺乳的中医调理治疗": "1 妇产科疾病 （124）/1.14 产后缺乳的中医调理治疗"
      - "1.15 孕期超声检查": "1 妇产科疾病 （124）/1.15 孕期超声检查"
      - "1.16 产前检查": "1 妇产科疾病 （124）/1.16 产前检查"
      - "1.17 产褥期护理": "1 妇产科疾病 （124）/1.17 产褥期护理"
      - "1.18 超声引导下消融治疗子宫肌瘤": "1 妇产科疾病 （124）/1.18 超声引导下消融治疗子宫肌瘤"
      - "1.19 超声引导下消融治疗子宫腺肌病": "1 妇产科疾病 （124）/1.19 超声引导下消融治疗子宫腺肌病"
      - "1.20 多囊卵巢综合征": "1 妇产科疾病 （124）/1.20 多囊卵巢综合征"
      - "1.21 多胎妊娠及减胎手术": "1 妇产科疾病 （124）/1.21 多胎妊娠及减胎手术"
      - "1.22 风湿病与妊娠": "1 妇产科疾病 （124）/1.22 风湿病与妊娠"
      - "1.23 分娩镇痛": "1 妇产科疾病 （124）/1.23 分娩镇痛"
      - "1.24 妇产科缺铁性贫血": "1 妇产科疾病 （124）/1.24 妇产科缺铁性贫血"
      - "1.25 附件炎": "1 妇产科疾病 （124）/1.25 附件炎"
      - "1.26 妇科症状-白带问题": "1 妇产科疾病 （124）/1.26 妇科症状-白带问题"
      - "1.27 妇科症状-妇科检查": "1 妇产科疾病 （124）/1.27 妇科症状-妇科检查"
      - "1.28 妇科症状-外阴问题": "1 妇产科疾病 （124）/1.28 妇科症状-外阴问题"
      - "1.29 妇科症状-下腹疼痛": "1 妇产科疾病 （124）/1.29 妇科症状-下腹疼痛"
      - "1.30 妇科症状-月经问题": "1 妇产科疾病 （124）/1.30 妇科症状-月经问题"
      - "1.31 妇科肿瘤影像学诊断": "1 妇产科疾病 （124）/1.31 妇科肿瘤影像学诊断"
      - "1.32 腹腔镜下子宫内膜癌分期手术": "1 妇产科疾病 （124）/1.32 腹腔镜下子宫内膜癌分期手术"
      - "1.33 腹腔镜下宫颈癌根治术": "1 妇产科疾病 （124）/1.33 腹腔镜下宫颈癌根治术"
      - "1.34 更年期综合征": "1 妇产科疾病 （124）/1.34 更年期综合征"
      - "1.35 宫颈癌//吴鸣教授": "1 妇产科疾病 （124）/1.35 宫颈癌//吴鸣教授"
      - "1.36 宫颈癌曹泽毅教授": "1 妇产科疾病 （124）/1.36 宫颈癌曹泽毅教授"
      - "1.37 宫颈癌及癌前病变的相关病理诊断": "1 妇产科疾病 （124）/1.37 宫颈癌及癌前病变的相关病理诊断"
      - "1.38 宫颈癌前病变": "1 妇产科疾病 （124）/1.38 宫颈癌前病变"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"
      - "": "1 妇产科疾病 （124）/"





  - 2 儿科疾病 134:
      - "蓬莱鬼话、玄幻灵异、中医命理 1-37篇": "2 儿科疾病 134/蓬莱鬼话、玄幻灵异、中医命理 1-37篇.md"
  - 3 神经系统疾病 110:
      - "金融财经、股市楼市、经济预测 1-50篇": "3 神经系统疾病 110/金融财经、股市楼市、经济预测 1-50篇.md"
      - "金融财经、股市楼市、经济预测 51-100篇": "3 神经系统疾病 110/金融财经、股市楼市、经济预测 51-100篇.md"
      - "金融财经、股市楼市、经济预测 101-127篇": "3 神经系统疾病 110/金融财经、股市楼市、经济预测 101-127篇.md"
  - 4 呼吸系统疾病 67:
      - "人在江湖、古今热点、成长箴言 1-35篇": "4 呼吸系统疾病 67/人在江湖、古今热点、成长箴言 1-35篇.md"
      - "人在江湖、古今热点、成长箴言 36-70篇": "4 呼吸系统疾病 67/人在江湖、古今热点、成长箴言 36-70篇.md"
  - 5 消化系统疾病 113:
      - "天涯高阶神贴1-50篇": "5 消化系统疾病 113/天涯高阶神贴1-50篇.md"
      - "天涯高阶神贴51-100篇": "5 消化系统疾病 113/天涯高阶神贴51-100篇.md"
      - "天涯高阶神贴101-150篇": "5 消化系统疾病 113/天涯高阶神贴101-150篇.md"
      - "天涯高阶神贴151-190篇": "5 消化系统疾病 113/天涯高阶神贴151-190篇.md"
  - 6 心脑血管系统疾病 97:
      - "KK大神": "6 心脑血管系统疾病 97/KK大神.md"
      - "懒兔子": "6 心脑血管系统疾病 97/懒兔子.md"
      - "九哥合集": "6 心脑血管系统疾病 97/九哥合集.md"
      - "蓬莲鬼话": "6 心脑血管系统疾病 97/蓬莲鬼话.md"
      - "禅海商道": "6 心脑血管系统疾病 97/禅海商道.md"
      - "股市楼市": "6 心脑血管系统疾病 97/股市楼市.md"
      - "缠中说禅": "6 心脑血管系统疾病 97/缠中说禅.md"
      - "创业家园": "6 心脑血管系统疾病 97/创业家园.md"
      - "经济论坛": "6 心脑血管系统疾病 97/经济论坛.md"
      - "国际观察": "6 心脑血管系统疾病 97/国际观察.md"
      - "盛京剑客": "6 心脑血管系统疾病 97/盛京剑客.md"
      - "地缘看世界": "6 心脑血管系统疾病 97/地缘看世界.md"
      - "大家常读的贴": "6 心脑血管系统疾病 97/大家常读的贴.md"
      - "开窍开悟开智5册": "6 心脑血管系统疾病 97/开窍开悟开智5册.md"
      - "独家稀有贴整理新增": "6 心脑血管系统疾病 97/独家稀有贴整理新增.md"
