site_name: 医学微视
site_url: https://yxws.zhihu.blog/
site_author: shutouyabo
site_description: >-
  wiki bin

repo_name: 医学微视
repo_url: https://github.com/shutouyabo/yixueweishi/

copyright: Copyright &copy; 2021-present <a href="https://github.com/shutouyabo" target="_blank" rel="noopener noreferrer">shutouyabo</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true

  - search:
      lang:
        - zh
  - git-revision-date:
  - minify:
      minify_html: true
  - open-in-new-tab:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shutouyabo/yixueweishi/
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - 前言: "index.md"
  - 1 妇产科疾病 （124）:
      - "1.1 瘢痕妊娠": "c01/c01_001.md"
      - "1.2 剖宫产后再生育注意事项": "c01/c01_002.md"
      - "1.3 剖宫产麻醉": "c01/c01_003.md"
      - "1.4 保胎": "c01/c01_004.md"
      - "1.5 备孕": "c01/c01_005.md"
      - "1.6 闭经": "c01/c01_006.md"
      - "1.7 避孕": "c01/c01_007.md"
      - "1.8 剖宫产术后护理": "c01/c01_008.md"
      - "1.9 产后避孕": "c01/c01_009.md"
      - "1.10 产后出血": "c01/c01_010.md"
      - "1.11 产后尿失禁": "c01/c01_011.md"
      - "1.12 产后排气、通便的治疗": "c01/c01_012.md"
      - "1.13 产后盆底功能恢复": "c01/c01_013.md"
      - "1.14 产后缺乳的中医调理治疗": "c01/c01_014.md"
      - "1.15 孕期超声检查": "c01/c01_015.md"
      - "1.16 产前检查": "c01/c01_016.md"
      - "1.17 产褥期护理": "c01/c01_017.md"
      - "1.18 超声引导下消融治疗子宫肌瘤": "c01/c01_018.md"
      - "1.19 超声引导下消融治疗子宫腺肌病": "c01/c01_019.md"
      - "1.20 多囊卵巢综合征": "c01/c01_020.md"
      - "1.21 多胎妊娠及减胎手术": "c01/c01_021.md"
      - "1.22 风湿病与妊娠": "c01/c01_022.md"
      - "1.23 分娩镇痛": "c01/c01_023.md"
      - "1.24 妇产科缺铁性贫血": "c01/c01_024.md"
      - "1.25 附件炎": "c01/c01_025.md"
      - "1.26 妇科症状-白带问题": "c01/c01_026.md"
      - "1.27 妇科症状-妇科检查": "c01/c01_027.md"
      - "1.28 妇科症状-外阴问题": "c01/c01_028.md"
      - "1.29 妇科症状-下腹疼痛": "c01/c01_029.md"
      - "1.30 妇科症状-月经问题": "c01/c01_030.md"
      - "1.31 妇科肿瘤影像学诊断": "c01/c01_031.md"
      - "1.32 腹腔镜下子宫内膜癌分期手术": "c01/c01_032.md"
      - "1.33 腹腔镜下宫颈癌根治术": "c01/c01_033.md"
      - "1.34 更年期综合征": "c01/c01_034.md"
      - "1.35 宫颈癌吴鸣教授": "c01/c01_035.md"
      - "1.36 宫颈癌曹泽毅教授": "c01/c01_036.md"
      - "1.37 宫颈癌及癌前病变的相关病理诊断": "c01/c01_037.md"
      - "1.38 宫颈癌前病变": "c01/c01_038.md"
      - "1.39 宫颈癌前病变的治疗": "c01/c01_039.md"
      - "1.40 宫颈机能不全": "c01/c01_040.md"
      - "1.41 宫颈炎廖秦平教授": "c01/c01_041.md"
      - "1.42 宫颈炎余立群教授": "c01/c01_042.md"
      - "1.43 宫腔镜": "c01/c01_043.md"
      - "1.44 功血": "c01/c01_044.md"
      - "1.45 HPV疫苗": "c01/c01_045.md"
      - "1.46 浆细胞性乳腺炎": "c01/c01_046.md"
      - "1.47 绝经后出血": "c01/c01_047.md"
      - "1.48 流产后避孕": "c01/c01_048.md"
      - "1.49 卵巢癌潘凌亚教授": "c01/c01_049.md"
      - "1.50 卵巢癌曹泽毅教授": "c01/c01_050.md"
      - "1.51 卵巢囊肿": "c01/c01_051.md"
      - "1.52 卵巢上皮癌": "c01/c01_052.md"
      - "1.53 卵巢生殖细胞肿瘤": "c01/c01_053.md"
      - "1.54 卵巢早衰": "c01/c01_054.md"
      - "1.55 卵巢储备功能降低": "c01/c01_055.md"
      - "1.56 卵巢组织冻存移植技术": "c01/c01_056.md"
      - "1.57 慢性盆腔痛": "c01/c01_057.md"
      - "1.58 母乳喂养": "c01/c01_058.md"
      - "1.59 母乳喂养常见问题": "c01/c01_059.md"
      - "1.60 女性外阴白斑": "c01/c01_060.md"
      - "1.61 女性不孕症": "c01/c01_061.md"
      - "1.62 女性绝经后骨质疏松": "c01/c01_062.md"
      - "1.63 女性尿失禁": "c01/c01_063.md"
      - "1.64 盆腔炎（附件炎）": "c01/c01_064.md"
      - "1.65 盆腔淤血综合征的介入治疗": "c01/c01_065.md"
      - "1.66 剖宫产": "c01/c01_066.md"
      - "1.67 剖宫产切口憩室": "c01/c01_067.md"
      - "1.68 妊高症(子痫前期)": "c01/c01_068.md"
      - "1.69 人工流产": "c01/c01_069.md"
      - "1.70 人乳头瘤病毒（HPV）感染": "c01/c01_070.md"
      - "1.71 妊娠甲状腺疾病": "c01/c01_071.md"
      - "1.72 妊娠剧吐的中医调理治疗": "c01/c01_072.md"
      - "1.73 妊娠剧吐": "c01/c01_073.md"
      - "1.74 妊娠期糖尿病": "c01/c01_074.md"
      - "1.75 乳腺结节微波消融术": "c01/c01_075.md"
      - "1.76 乳腺纤维腺瘤（乳腺纤维瘤）": "c01/c01_076.md"
      - "1.77 乳腺叶状肿瘤": "c01/c01_077.md"
      - "1.78 乳腺肿瘤的超声诊断及介入治疗": "c01/c01_078.md"
      - "1.79 三阴性乳腺癌": "c01/c01_079.md"
      - "1.80 生殖健康": "c01/c01_080.md"
      - "1.81 试管婴儿": "c01/c01_081.md"
      - "1.82 输卵管畸形": "c01/c01_082.md"
      - "1.83 输卵管炎": "c01/c01_083.md"
      - "1.84 胎儿畸形超声筛查诊断": "c01/c01_084.md"
      - "1.85 胎儿水肿": "c01/c01_085.md"
      - "1.86 胎儿心脏病多学科会诊": "c01/c01_086.md"
      - "1.87 胎停育（过期流产）": "c01/c01_087.md"
      - "1.88 痛经": "c01/c01_088.md"
      - "1.89 晚期乳腺癌的诊治": "c01/c01_089.md"
      - "1.90 围产期脑卒中": "c01/c01_090.md"
      - "1.91 围绝经期综合征": "c01/c01_091.md"
      - "1.92 无痛人流麻醉": "c01/c01_092.md"
      - "1.93 先兆早产的中医调理治疗": "c01/c01_093.md"
      - "1.94 先兆流产的中医调理治疗": "c01/c01_094.md"
      - "1.95 习惯性流产": "c01/c01_095.md"
      - "1.96 压力大与妇科疾病": "c01/c01_096.md"
      - "1.97 羊水过多的中医调理治疗": "c01/c01_097.md"
      - "1.98 阴道炎": "c01/c01_098.md"
      - "1.99 阴道再造术": "c01/c01_099.md"
      - "1.100 异位妊娠（宫外孕）": "c01/c01_100.md"
      - "1.101 优生遗传咨询": "c01/c01_101.md"
      - "1.102 月经不调王必勤教授": "c01/c01_102.md"
      - "1.103 月经不调牛建昭教授": "c01/c01_103.md"
      - "1.104 月经过多": "c01/c01_104.md"
      - "1.105 月经量少": "c01/c01_105.md"
      - "1.106 孕期补钙": "c01/c01_106.md"
      - "1.107 孕期常见问题": "c01/c01_107.md"
      - "1.108 孕期营养": "c01/c01_108.md"
      - "1.109 孕早期常见问题": "c01/c01_109.md"
      - "1.110 孕期常见症状": "c01/c01_110.md"
      - "1.111 早产": "c01/c01_111.md"
      - "1.112 针灸防治卵巢早衰": "c01/c01_112.md"
      - "1.113 中医治疗不孕症": "c01/c01_113.md"
      - "1.114 中医治疗经前期综合征": "c01/c01_114.md"
      - "1.115 中医治疗卵巢早衰": "c01/c01_115.md"
      - "1.116 中医治疗乳痛": "c01/c01_116.md"
      - "1.117 子宫肌瘤": "c01/c01_117.md"
      - "1.118 子宫肌瘤的介入治疗": "c01/c01_118.md"
      - "1.119 子宫内膜癌": "c01/c01_119.md"
      - "1.120 子宫内膜异位症": "c01/c01_120.md"
      - "1.121 子宫内膜息肉": "c01/c01_121.md"
      - "1.122 子宫脱垂": "c01/c01_122.md"
      - "1.123 子宫腺肌病": "c01/c01_123.md"
      - "1.124 孕期水肿": "c01/c01_124.md"
  - 2 儿科疾病 134:
      - "2.1 矮小症": "2 儿科疾病 134/2.1 矮小症.md"
      - "2.2 Alport综合征": "2 儿科疾病 134/2.2 Alport综合征.md"
      - "2.3 白化病": "2 儿科疾病 134/2.3 白化病.md"
      - "2.4 半乳糖血症": "2 儿科疾病 134/2.4 半乳糖血症.md"
      - "2.5 蚕豆病": "2 儿科疾病 134/2.5 蚕豆病.md"
      - "2.6 肠梗阻患儿的护理": "2 儿科疾病 134/2.6 肠梗阻患儿的护理.md"
      - "2.7 肠套叠患儿的护理": "2 儿科疾病 134/2.7 肠套叠患儿的护理.md"
  - 3 神经系统疾病 110:
      - "金融财经、股市楼市、经济预测 1-50篇": "3 神经系统疾病 110/金融财经、股市楼市、经济预测 1-50篇.md"
      - "金融财经、股市楼市、经济预测 51-100篇": "3 神经系统疾病 110/金融财经、股市楼市、经济预测 51-100篇.md"
      - "金融财经、股市楼市、经济预测 101-127篇": "3 神经系统疾病 110/金融财经、股市楼市、经济预测 101-127篇.md"
  - 4 呼吸系统疾病 67:
      - "人在江湖、古今热点、成长箴言 1-35篇": "4 呼吸系统疾病 67/人在江湖、古今热点、成长箴言 1-35篇.md"
      - "人在江湖、古今热点、成长箴言 36-70篇": "4 呼吸系统疾病 67/人在江湖、古今热点、成长箴言 36-70篇.md"
  - 5 消化系统疾病 113:
      - "天涯高阶神贴1-50篇": "5 消化系统疾病 113/天涯高阶神贴1-50篇.md"
      - "天涯高阶神贴51-100篇": "5 消化系统疾病 113/天涯高阶神贴51-100篇.md"
      - "天涯高阶神贴101-150篇": "5 消化系统疾病 113/天涯高阶神贴101-150篇.md"
      - "天涯高阶神贴151-190篇": "5 消化系统疾病 113/天涯高阶神贴151-190篇.md"
  - 6 心脑血管系统疾病 97:
      - "KK大神": "6 心脑血管系统疾病 97/KK大神.md"
      - "懒兔子": "6 心脑血管系统疾病 97/懒兔子.md"
      - "九哥合集": "6 心脑血管系统疾病 97/九哥合集.md"
      - "蓬莲鬼话": "6 心脑血管系统疾病 97/蓬莲鬼话.md"
      - "禅海商道": "6 心脑血管系统疾病 97/禅海商道.md"
      - "股市楼市": "6 心脑血管系统疾病 97/股市楼市.md"
      - "缠中说禅": "6 心脑血管系统疾病 97/缠中说禅.md"
      - "创业家园": "6 心脑血管系统疾病 97/创业家园.md"
      - "经济论坛": "6 心脑血管系统疾病 97/经济论坛.md"
      - "国际观察": "6 心脑血管系统疾病 97/国际观察.md"
      - "盛京剑客": "6 心脑血管系统疾病 97/盛京剑客.md"
      - "地缘看世界": "6 心脑血管系统疾病 97/地缘看世界.md"
      - "大家常读的贴": "6 心脑血管系统疾病 97/大家常读的贴.md"
      - "开窍开悟开智5册": "6 心脑血管系统疾病 97/开窍开悟开智5册.md"
      - "独家稀有贴整理新增": "6 心脑血管系统疾病 97/独家稀有贴整理新增.md"
